### ISSUE TITLE
Common lint rule

### ISSUE THREAD

**Issue by djKooks** [paypay/paypayopa-sdk-python#12]
Is there some kind of common lint rule(or tool) to apply? 
If there is, it will be good to comment on README, or make one if not.

**Comment by shreyanshp** [comment]
I think `pylint` should do, we should also enable it on each PR's through travis
@djKooks if you have any thoughts on this you can raise a PR!

**Comment by djKooks** [comment]
@shreyanshp thanks~I'll update and let you know

**Comment by djKooks** [comment]
@shreyanshp I've setup some config file for linting rule(so many errors now...).
I think we need to decide several rules to be ignored...how do you think?

**Comment by shreyanshp** [comment]
@solancer have a look at #14 and decide which rules to be ignored

@djKooks Great job, buddy!

**Comment by solancer** [comment]
@djKooks hi, I'm inclined towards using something like **pylama** which has no config linting based and code audit check. This is easy to use and also we don't have to define our own rules. 

Let me know your thought.

<img width="1435" alt="Screenshot 2020-08-27 at 3 16 03 am" src="https://user-images.githubusercontent.com/800668/91360373-fa533080-e813-11ea-8dd4-4fff0dc0531e.png">

<img width="583" alt="Screenshot 2020-08-27 at 3 17 35 am" src="https://user-images.githubusercontent.com/800668/91360365-f7584000-e813-11ea-9e8d-eeb196b634fe.png">

**Comment by djKooks** [comment]
@solancer thanks for suggestion~
I've just tested pylama. It seems easy to use, but rule seems too loose. I can find only one lint issue:
<img width="736" alt="Screen Shot 2020-08-27 at 12 38 36" src="https://user-images.githubusercontent.com/1720209/91381429-58a70000-e862-11ea-8285-52d6ff2c29e1.png">

I think using `pylama` is okay, but need to add some additional rule.

**Comment by solancer** [comment]
@djKooks yes pylama has provision to support  linting rules

![Screenshot 2020-08-27 at 11 22 01 am](https://user-images.githubusercontent.com/800668/91394548-445e0580-e858-11ea-925f-f0e31f8fd648.png)

**Comment by djKooks** [comment]
@solancer just tested with pylama and it seems working well. No problem on using this. But there are few things I'm worried.

[1] I've tried using `pytest --pylama`, and it shows error like:
<img width="1402" alt="Screen Shot 2020-08-27 at 16 42 48" src="https://user-images.githubusercontent.com/1720209/91412313-9583ee80-e884-11ea-85a7-f1f9d949671e.png">

[2] And in official doc, it seem does not supports Python 3.8 yet.

**Comment by shreyanshp** [comment]
closed by #40
