### ISSUE TITLE
There is no Merged code in PyPI(Python Package Index)

### ISSUE THREAD

**Issue by daikidomon** [paypay/paypayopa-sdk-python#55]
There is no Merged code in PyPI.
But, The pull request is authorized, and codes are merged.
PR => https://github.com/paypay/paypayopa-sdk-python/pull/52

Please let me know if there are any additional processes for merging to PyPI.

**Comment by shreyanshp** [comment]
It would be released by tomorrow 
@solancer

**Comment by shreyanshp** [comment]
Released in v1.0.1
