### ISSUE TITLE
Throw exception when use in AWS Lambda.

### ISSUE THREAD

**Issue by fill9120** [paypay/paypayopa-sdk-python#59]
**Describe the bug**
I created an AWS Lambda function using Chalice, but when I import paypayopa, it throws an exception.  
The exceptions are:

```
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'app': invalid syntax (uuid.py, line 138)
Traceback (most recent call last):
   File "/var/task/uuid.py" Line 138
                 if not 0 <= time_low < 1<<32L:
```

**To Reproduce**

The minimum source code to reproduce is:

**requirements.txt**

```
paypayopa
```

**app.py**

```
import paypayopa
from chalice import Chalice

app = Chalice(app_name='app_name')


@app.route('/')
def index():
    return {'hello': 'world'}
```

**Expected behavior**
I think it's because uuid is installed.  
https://stackoverflow.com/questions/33612977/how-to-use-uuid-lib-with-mod-wsgi  

For example, if you remove uuid from setup.py like [this repository](https://github.com/fill9120/paypayopa-sdk-python), it works as expected.

**requirements.txt**

```
git+https://github.com/fill9120/paypayopa-sdk-python.git
```

**app.py**

Same as above

**Comment by shreyanshp** [comment]
@solancer please check this

**Comment by solancer** [comment]
@fill9120 Thank you for catching this, we will send out a fix shortly by getting rid of UUID as a dependency.

**Comment by fill9120** [comment]
@solancer Thank you for the quick fix!
