### ISSUE TITLE
支払い詳細の取得に失敗しました ページを再読み込みし、再度お試しください

### ISSUE THREAD

**Issue by lalawila** [paypay/paypayopa-sdk-python#61]
![image](https://user-images.githubusercontent.com/26580242/108322825-e4da2480-7200-11eb-9258-b0d73382e3e2.png)

In sandbox test. 
Payment page show fail message.

It's also a failure to pay in paypay if open with url(universal link).
I remember it was successful a few days ago.

But I can pay success in paypay app if open with deeplink.

Success of create_qr_code.

`{
	'resultInfo': {
		'code': 'SUCCESS',
		'message': 'Success',
		'codeId': '08100001'
	},
	'data': {
		'codeId': '04-7fN9dRZkbj5M37lO',
		'url': 'https://qr-stg.sandbox.paypay.ne.jp/281801047fN9dRZkbj5M37lO',
		'expiryDate': 1613634765,
		'merchantPaymentId': '202102180014',
		'amount': {
			'amount': 1,
			'currency': 'JPY'
		},
		'orderDescription': 'Example - Mune Cake shop',
		'orderItems': [{
			'name': 'Moon cake',
			'category': 'pasteries',
			'quantity': 1,
			'productId': '67678',
			'unit_price': {
				'amount': 1,
				'currency': 'JPY'
			}
		}],
		'codeType': 'ORDER_QR',
		'requestedAt': 1613634464,
		'redirectUrl': 'http://foobar.com',
		'redirectType': 'WEB_LINK',
		'isAuthorization': False,
		'deeplink': 'paypay://payment?link_key=https%3A%2F%2Fqr-stg.sandbox.paypay.ne.jp%2F281801047fN9dRZkbj5M37lO'
	}

 }`

Success of get_payment_details.
`{
	'resultInfo': {
		'code': 'SUCCESS',
		'message': 'Success',
		'codeId': '08100001'
	},
	'data': {
		'status': 'CREATED',
		'acceptedAt': 0,
		'requestedAt': 0
	}
}
`

**Comment by shreyanshp** [comment]
@solancer please check this

**Comment by solancer** [comment]
Hi @lalawila , we looked into the issue you reported however we are not able to recreate it on our end. We assumed this was intermittent and started to observe for any errors and logs, as of now we haven’t been able to find anything. We are closing this issue, but please do get back to us in case you face this issue again you also write to us at opensource@paypay-corp.co.jp
