### ISSUE TITLE
The official document is wrong.

### ISSUE THREAD

**Issue by Alpaca131** [paypay/paypayopa-sdk-python#66]
**Describe the bug**
The official documents have many wrong points.
(https://developer.paypay.ne.jp/products/docs/webpayment)

**To Reproduce**
Just run the sample code.

**Expected behavior**
Run successfully without any error.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows10
 - Browser: Microsoft Edge
 - Version: 90.0.818.51
 - Device: Desktop
 - Python:  3.8.8
 - paypayopa: 1.0.4

**Additional context**
The ~~intent~~ indent is wrong.
The code raises "AttributeError". It's trying to access dict by dot notation.
``
AttributeError: 'dict' object has no attribute 'resultInfo'
``
When I clicked the copy button of the documents,  it copies all text includes comments, so I can't paste that to the shell.

Other language's sample is also wrong.
Eg. the Node.js sample is missing a single quote in some places.

**Comment by javidlulu** [comment]
@solancer please check this

**Comment by solancer** [comment]
@Alpaca131 Thanks got raising this issue with us on the documentation typo, we are sending in a fix.

Below is the correct version for python

```
print(response['resultInfo']['code'])
```

**Comment by Alpaca131** [comment]
It worked!
Thank you for your response.

**Comment by solancer** [comment]
closing the issue, as fix on official docs has been raised
